#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Cloud images may hard code the eth0 interfaces so they
# boot with DHCP.

# Fedora
rm -f /etc/sysconfig/network-scripts/ifcfg-eth*

# Ubuntu
rm -f /etc/network/interfaces.d/eth*

# Debian
rm -f /etc/network/interfaces.d/eth*

# Gentoo
rm -f /etc/conf.d/net*
